# La definicion de la version es obligatoria para el reconocimiento de la sintaxis,
# en el caso especifico de las anclas, en vscode de no tenerla marca duplicacion de claves
# aunque no exista tal duplicacion
version: "3.9"
x-common-base: &mem-limit
  deploy:
    resources:
      limits:
        memory: 700m

x-spring-env: &spring-env
  SPRING_PROFILES_ACTIVE: default
  SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
  SPRING_RABBITMQ_HOST: "rabbit"

x-common-net: &network
  networks:
    - eazybank

services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    <<: *network
  configserver:
    image: "albertoesteva88/configserver:s6"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    <<:
      - *mem-limit
      - *network
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
  accounts:
    image: "albertoesteva88/accounts:s6"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    <<:
      - *mem-limit
      - *network
    environment:
# Cuando usas SPRING_CONFIG_IMPORT para conectarte al Config Server,
# Spring necesita conocer el nombre de la aplicación lo antes posible
# incluso antes de cargar el YAML del microservicio.
# Por lo que tambien lo agregamos como variable de entorno
      SPRING_APPLICATION_NAME: accounts
      <<: *spring-env
  loans:
    image: "albertoesteva88/loans:s6"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    <<:
      - *mem-limit
      - *network
    environment:
      SPRING_APPLICATION_NAME: loans
      <<: *spring-env
  cards:
    image: "albertoesteva88/cards:s6"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    <<:
      - *mem-limit
      - *network
    environment:
      SPRING_APPLICATION_NAME: cards
      <<: *spring-env
networks:
  eazybank:
    driver: "bridge"